"""Authenticate current source closure and explicitly retained interval inputs.

Retained inputs were not regenerated by the current producers. Their complete
mathematical payload was compared exactly during packaging to archived originals.
The private archival source bindings were checked before that comparison. This
module checks current distribution integrity; it does not recompute integrals.
Fresh producer outputs instead carry and must match their actual source hashes.
"""
from pathlib import Path
import hashlib,json
HERE=Path(__file__).resolve().parent
def canonical(data):
    return json.dumps(data,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode('utf-8')
def current_sources():
    manifest=json.loads((HERE/'Inputs.json').read_text(encoding='utf-8'))
    for name,digest in manifest['currentSources'].items():
        if hashlib.sha256((HERE/name).read_bytes()).hexdigest()!=digest:
            raise ValueError('Current certificate source changed: '+name)
    return manifest
def check_binding(data,bindings):
    manifest=current_sources()
    provenance=data.get('retainedEnclosure')
    if provenance is not None:
        if provenance.get('kind')!='retained-directed-enclosure':
            raise ValueError('Unrecognized retained-input provenance')
        name=provenance.get('input')
        row=manifest['retainedInputs'].get(name)
        if row is None or row['documentSha256']!=hashlib.sha256(canonical(data)).hexdigest():
            raise ValueError('Retained input identity mismatch')
        if any(key in data for key in bindings):
            raise ValueError('Retained input must not claim current producer generation')
        if sorted(path.name for path in bindings.values())!=sorted(row['correspondingCurrentProducers']):
            raise ValueError('Wrong retained input/producer correspondence')
        return 'retained-enclosures; numerical payload unchanged; not regenerated'
    for key,path in bindings.items():
        if data.get(key)!=hashlib.sha256(path.read_bytes()).hexdigest():
            raise ValueError('Fresh producer binding mismatch: '+key)
    return 'fresh producer source bindings'
